### PR TITLE
Update to Scala 2.11.8 and improve error reporting if JAVA6_HOME is not defined

### PR DESCRIPTION
**Pull request by ijuma**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
@nbauernfeind probably conflicts with the other PR, but I think this fix first makes sense, then add cross-compilation for 2.12.

**Comment by JoshRosen** [comment]
Yep, it does conflict but I rebased my PR. Unless I'm mistaken, I think that we also have to bump the Scala version in `.travis.yml`. Should I do that in my PR?

**Comment by cowtowncoder** [comment]
@JoshRosen I assume that makes sense. Hoping @nbauernfeind gets a chance to chime in too, although if he's busy I can merge this tomorrow anyway.

**Comment by nbauernfeind** [comment]
This PR is beautiful and very clear. Thanks for your contribution!

**Pull request merged**
