### PR TITLE
sbt 0.13.17

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
please merge @mbknor

**Comment by sullis** [comment]
ping @mbknor  @brharrington

**Comment by brharrington** [comment]
@sullis I'm not a maintainer, there isn't much I can do to help move this along.

**Comment by sullis** [comment]
ready for merge.

**Comment by mbknor** [comment]
why is this so big deal? I might merge it when I'm sitting down with this module.

**Comment by mbknor** [comment]
Ok.. thanks for the info. 
In the next PR, give some more info :)

I'll merge it.

**Pull request merged**
