### PR TITLE
Scala 2.13.0 rc1

### PR DESCRIPTION
**Pull request by pjfanning**
https://github.com/FasterXML/jackson-module-scala/issues/405

### CODE REVIEW

**Comment by seratch** [comment]
Hi maintainers, could you take a look at this pull request? I am also waiting for a new version release for Scala 2.13.0-RC1.

**Comment by pjfanning** [comment]
@nbauernfeind @mbknor would it be possible to merge this and publish a 2.13.0-RC1 version of the jar?

**Comment by alexarchambault** [comment]
It would be really cool to have this (or any kind of `2.13.0-RC1` support) merged and released :|

**Comment by alexarchambault** [comment]
Don't know who can merge and release… Maybe @nbauernfeind?

**Comment by nbauernfeind** [comment]
I will spend some time with this tonight. Please ping me in ~2 days if you don't hear of or see a release for 2.13.0-RC1.

**Comment by mbknor** [comment]
I'm going to merge and release this one now

**Comment by nbauernfeind** [comment]
Sweet! Thanks =).

**Comment by mbknor** [comment]
Version for 2.13.0-RC1 is on its way to maven central

**Comment by alexarchambault** [comment]
Thanks a lot @mbknor @nbauernfeind!

**Comment by mbknor** [comment]
Sorry for it taking so long... Please ping me if the jar does not arrive in the maven central..

**Pull request merged**
