### PR TITLE
fixed #401: Deserialization of inner Enumeration class fails

### LINKED ISSUE #401: Deserialization of inner Enumeration class fails
The (de)serialization of top level Enumeration classes works well.  But if you put the Enumeration class inside another object the deserialization fails with a ClassNotFoundException.

Example code:
```
object JsonTest extends App {

	object Kind extends Enumeration {
		type Kind = Value
		val text = Value
	}

	val jsonCode = JsonUtils.toJson(Kind.text)
	println(jsonCode)
	println(JsonUtils.fromJson[Kind.Value](jsonCode))

}
```

### PR DESCRIPTION
**Pull request by xylo**
This pull request fixes issue #401.

### CODE REVIEW

**Comment by nbauernfeind** [comment]
This fix looks good. I appreciate the additional test. Thanks!

Can you fix the formatting though? I see that tabs are not expanded into spaces which results in messy whitespace.

**Comment by xylo** [comment]
OK.

**Comment by xylo** [comment]
OK. I fixed the indentation.

**Comment by nbauernfeind** [comment]
LGTM. Thanks!

**Pull request merged**
