### PR TITLE
Cross-build for Scala 2.12.0-M5

### PR DESCRIPTION
**Pull request by jodersky**
* Upgrade 2.12 version to latest milestone, M5
* Upgrade Scalatest version to work with latest Scala version

### CODE REVIEW

**Comment by christophercurrie** [comment]
Thanks for this. Is ScalaTest 3.0 required for Scala 2.12 M5 support?

**Comment by jodersky** [comment]
Yes, scalatest only supports scala 2.12.0-M5 in its latest release, namely 3.0.0-RC4.

I remember the Akka maintainers asking for a 2.2.x release, however they ended up upgrading in the end, so I can't say for sure, but it seems that 2.2.x will not be supported.

**Comment by christophercurrie** [comment]
I'm a little reluctant to move the whole project to an RC build dependency. Is 3.0 blocked on 2.12, or do they plan to release it soon?

**Comment by jodersky** [comment]
I don't know when they plan to release, but my guess is that 2.12 will be final before scalatest 3.0 comes out.
Scalatest has generally been very "careful" and the 3-RC series have been out for quite a while, nevertheless I can understand your concern. Would a scala-version conditional dependency on scalatest be an option?
Something like
```scala
val scalaTestVersion = Def.setting{scalaVersion.value match {
  case "2.12.0-M5" => "3.0.0-RC4"
  case _ => "2.2.6"
}}
libraryDependencies += "org.scalatest" %% "scalatest" % scalaTestVersion.value % "test"
```

**Comment by christophercurrie** [comment]
That'd be perfect. Would the changes to the tests work under both versions?

**Comment by jodersky** [comment]
I'm just trying it out, be back in a couple of minutes

**Comment by jodersky** [comment]
everything worked locally :) (the changes in the tests were just replacements of deprecated imports)
I'll push the changes to this PR

**Comment by christophercurrie** [comment]
Perfect. Thanks for the contribution. 2.8.1 (when it releases) will support M5.

**Pull request merged**
