### PR TITLE
support Scala 2.12.0

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by umcodemonkey** [comment]
The version of ScalaTest being used doesn't support 2.12.0; please validate that tests pass before submitting PRs.

Also, 2.12.0 support has been added to version 2.8.5 of this module, so I would recommend upgrading if you need 2.12.0 support.

**Comment by christophercurrie** [comment]
The version of ScalaTest being used doesn't support 2.12.0; please validate that tests pass before submitting PRs.

Also, 2.12.0 support has been added to version 2.8.5 of this module, so I would recommend upgrading if you need 2.12.0 support.

**Comment by cowtowncoder** [comment]
FWTW `2.6` branch is not open any more so new releases are planned to be released for any of the component. 2.7 and 2.8 are still open; 2.7 for just one more release (2.7.9).

**Comment by pjfanning** [comment]
I did a separate patch for this on my fork of jackson-module-scala and fixed the issues with scalatest by upgrading it and by making a few small adjustments to imports in some tests that were out of date. 2 tests do fail with scala 2.12 and not with earlier scala versions.
https://travis-ci.org/pjfanning/jackson-module-scala/jobs/182792254

**Comment by cowtowncoder** [comment]
One more comment: if module maintainers want to do it, releasing 2.6.6 of just Scala 2.12 module could work since it's separate artifact from 2.10 and 2.11... as long as build tool can manage that (I assume sbt is pretty powerful, just not sure how easy it is to bend to do that).

Same question is relevant wrt 2.7 as well: 2.7.8 is out for 2.10 and 2.11 but 2.12 would be nice.
But with that we will do at least 2.7.9 still so it's less of a problem I suppose.

**Comment by mbknor** [comment]
Since I've just release version 2.6.7.1 of jackson-module-scala - with scala 2.12-support, this PR is no longer needed.

**Comment by cowtowncoder** [comment]
@mbknor Thank you sir!

**Pull request closed without merging**
